### ISSUE TITLE
php編集中に重くなる

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#22]
2chでみたのであとでソース貼ります。
なんでもlet php_folding=1してると、使ってるうちに超遅くなるとのこと。
folding自体は使ってないらしい。

**Comment by koron** [comment]
http://hibari.2ch.net/test/read.cgi/unix/1308288838/661-667n

一部抜粋:

> 例えば、a.phpとb.phpを開いてる時にa.phpの入力でかなり重くなるんだけど、b.phpに切り替えたらそっちは重くない 
> それからまたa.phpに戻すとやっぱり重い 
> で、1回gvimを起動しなおすと、a.phpの入力も重くならない 
> 
> 数時間編集するとこうなるみたいだから、undoの履歴が溜まって重くなってるとかかな？

途中経過:

> 上記関数は、set undofileだと所有者が自分の以外だとなぜかundofileは作れても、 
> うちの環境だと読み込み出来ないから、この関数使ってしのいでる 
> 
> この関数を無効化して、set undofileにしてみたけど、しばらく経つと同じ問題が発生する 
> ちなみに重くなってる時にtop見るとgvimのCPU使用率が100%になってる 

解決報告:

> なんで入力が遅くなるのか分からんが、どうやら~/.vimrcに書いてあった 
> 　　let php_folding = 1 
> が原因だったみたい 
> folding元々使ってなかったからこれで解決した

**Comment by ynkdir** [comment]
関係ありそうなtodo

todo.txt
Slow combination of folding and PHP syntax highlighting.  Script to reproduce
it.  Caused by "syntax sync fromstart" in combination with patch 7.2.274.
(Christian Brabandt, 2010 May 27)
Generally, folding with 'foldmethod' set to "syntax" is slow.  Do profiling to
find out why.

時間経過で遅くなるってのが謎ですね。

**Comment by koron** [comment]
直感的には、(syntax)foldingロジックに変なバッファの履歴をみるような構造がある、
ってところですかねぇ。

**Comment by tyru** [comment]
twitterでKoRoNさんに関係ないと言われましたが一応貼っときます。

http://b.hatena.ne.jp/entry/d.hatena.ne.jp/sugarbabe335/20101030/1288450166

> syntax/php.vim で source syntax/html.vim して htmlのシンタックスをハイライトしてるからでした。

**Comment by koron** [comment]
Thanks! ってそのページprivate設定されて、本体見れなくなってるw
